<a href="https://colab.research.google.com/github/OlegSV117/project/blob/dev-kraken/%D0%9B%D0%B8%D0%BD%D0%90%D0%BB%D0%B32.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Все задания рекомендуется делать вручную, затем проверяя полученные результаты с использованием numpy.

1. Установить, какие произведения матриц  𝐴𝐵  и  𝐵𝐴  определены, и найти размерности полученных матриц:

а)  𝐴  — матрица  4×2 ,  𝐵  — матрица  4×2 ;

**Ответ**: произведение невозможно так как $2 \neq 4$


б)  𝐴  — матрица  2×5 ,  𝐵  — матрица  5×3 ;

**Ответ**: $(AB)_{2x3}$


в)  𝐴  — матрица  8×3 ,  𝐵  — матрица  3×8 ;
**Ответ**: $(AB)_{8x8}$


г)  𝐴  — квадратная матрица  4×4 ,  𝐵  — квадратная матрица  4×4 .

Ответ: $(AB)_{4x4}$

    
__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

**Решение**:$ A\cdot B =  \begin{pmatrix}
4 & -11\\ 
12 & -3
\end{pmatrix} .$

In [4]:
A = np.array([[1, -2], [3, 0]])
B = np.array ([[4, -1], [0, 5]])

print(f'Матрица A\n{A}')
print(f'Матрица B\n{B}')
print(f'Матрица AB\n{np.dot(A, B)}')

Матрица A
[[ 1 -2]
 [ 3  0]]
Матрица B
[[ 4 -1]
 [ 0  5]]
Матрица AB
[[  4 -11]
 [ 12  -3]]


__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

**Решение**: $3A-2B+4C=\begin{pmatrix}
11 & -5\\ 
9 & -12
\end{pmatrix}$,

In [8]:
A = np.array([[1, 7], [3, -6]])
B = np.array ([[0, 5], [2, -1]])
C = np.array ([[2, -4], [1, 1]])

print(f'Матрица A\n{A}')
print(f'Матрица B\n{B}')
print(f'Матрица C\n{C}')
print(f'Матрица 3𝐴−2𝐵+4𝐶 \n{3*A + (-2)*B + 4*C}')

Матрица A
[[ 1  7]
 [ 3 -6]]
Матрица B
[[ 0  5]
 [ 2 -1]]
Матрица C
[[ 2 -4]
 [ 1  1]]
Матрица 3𝐴−2𝐵+4𝐶 
[[ 11  -5]
 [  9 -12]]


__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.


Решение:
$A^T=\begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3\\ 
\end{pmatrix}$.

In [20]:
A = np.array([[4, 1], [5, -2], [2, 3]])
print(f'Матрица A\n{A}')
print(f'Транспонированная матрица A\n{A.T}')
print(f'A*At\n{np.dot(A, A.T)}')
print(f'At*A\n{np.dot(A.T, A)}')

# print(f'A*At\n{A.dot(A.T)}')

Матрица A
[[ 4  1]
 [ 5 -2]
 [ 2  3]]
Транспонированная матрица A
[[ 4  5  2]
 [ 1 -2  3]]
A*At
[[17 18 11]
 [18 29  4]
 [11  4 13]]
At*A
[[45  0]
 [ 0 14]]






__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [28]:

import numpy as np

A = np.array([[1, -2], [3, 0], [0, 5], [2, 5]])
B = np.array([[4, -1, 4], [0, 5, 6]])

def composition(A,B):
    m= A.shape[0]
    n= B.shape[1]
    k = A.shape[1]
    C = np.zeros((m,n)) 
    for i in range(0, m):
      for j in range(0, n):
        for ii in range(0, k):
          C[i][j]+= A[i][ii]*B[ii][j]
    return C


print(f'Произведение матриц   при помощи функции composition \n{composition (A,B)}')
print(f'Произведение матриц при помощи стандартной функции .dot\n{A.dot(B)}')

Произведение матриц   при помощи функции composition 
[[  4. -11.  -8.]
 [ 12.  -3.  12.]
 [  0.  25.  30.]
 [  8.  23.  38.]]
Произведение матриц при помощи стандартной функции .dot
[[  4 -11  -8]
 [ 12  -3  12]
 [  0  25  30]
 [  8  23  38]]


Все задания рекомендуется выполнять вручную, затем проверяя полученные результаты с использованием Numpy.

__1.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$
Решение: detA = $sinx^2+cosx^2$ = 1

In [14]:
import numpy as np
import scipy.linalg
x=1
a = np.array([[np.sin(x), - np.cos(x)], [np.cos(x), np.sin(x)]])
print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')

Матрица:
[[ 0.84147098 -0.54030231]
 [ 0.54030231  0.84147098]]
Определитель:
1


   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix} = 4*5*9 = 180;$$

In [15]:
a = np.array([[4,2,3], [0,5,1], [0,0,9]])
print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')

Матрица:
[[4 2 3]
 [0 5 1]
 [0 0 9]]
Определитель:
180


    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix} = 1*5*9+2*6*7+4*8*3 - 7*5*3- 1*8*6- 2*4*9$$

In [19]:
print(1*5*9+2*6*7+4*8*3 - 7*5*3- 1*8*6- 2*4*9)

a = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')

0
Матрица:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Определитель:
0


__2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})= (det(A))^{2}= 16$;
    
   б) $det(A^{T})= det(A)= 4$;
    
   в) $det(2A)= 2\cdot det(A)= 8$.

__3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

In [21]:
a = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])
print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')

Матрица:
[[ -2   7  -3]
 [  4 -14   6]
 [ -3   7  13]]
Определитель:
0


__4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$


**Решение:** rank(A) = 2 так как 1 и 3 строка линейно зависимы, определитель мвтрицы 2х2 не равен нулю

In [24]:
a = np.array([[1,2,3],[1,1,1],[2,3,4]])
r = np.linalg.matrix_rank(a)

print(f'Ранг матрицы: {r}')

Ранг матрицы: 2



   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

**Решение:** rank(A) = 3 так как 4 четвертая строка является лин комбинацей   1 и 2 строка. остальные строки линейно независимы (минор 3-его порядка  не равен 0)

In [25]:
a = np.array([[0,0,2,2],[0,0,2,2],[0,0,4,3], [2,3,5,6]])
r = np.linalg.matrix_rank(a)

print(f'Ранг матрицы: {r}')

Ранг матрицы: 3
