<a href="https://colab.research.google.com/github/OlegSV117/project/blob/dev-kraken/%D0%9B%D0%B8%D0%BD%D0%90%D0%BB%D0%B34.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

__1.__ Решить систему уравнений методом Гаусса:

$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4.
\end{cases}$$


**Ответ**: если $x_4 = C$, то  $$x_3 = 1,5 C-2$$,

$$ x_2 = 6,5 C$$, $$x_1 = 2-3C$$

__2.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:

   а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$
    
   в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases}$



In [19]:
# Задание а) 
import numpy as np
import scipy.linalg
a = np.array([[3,-1,1],[2,-5,-3],[1,1,-1]])
aa = np.array([[3,-1,1, 4],[2,-5,-3,-17],[1,1,-1,0]])
r = np.linalg.matrix_rank(a)
rr = np.linalg.matrix_rank(aa)
print(a)
print(aa)
print(f'Ранг матрицы: {r}')
print(f'Ранг расширенной матрицы: {rr}')


[[ 3 -1  1]
 [ 2 -5 -3]
 [ 1  1 -1]]
[[  3  -1   1   4]
 [  2  -5  -3 -17]
 [  1   1  -1   0]]
Ранг матрицы: 3
Ранг расширенной матрицы: 3


a)   Так как $rankA=rank \tilde A=3$ — число неизвестных, то система определена, т. е. имеет единственное решение;

In [20]:
# Задание б) 
import numpy as np
import scipy.linalg
a1 = np.array([[2,-4,6],[1,-2,3],[3,-6,9]])
aa1 = np.array([[2,-4,6, 1],[1,-2,3, -2],[3,-6,9, 5]])
r = np.linalg.matrix_rank(a1)
rr = np.linalg.matrix_rank(aa1)
print(a1)
print(aa1)
print(f'Ранг матрицы: {r}')
print(f'Ранг расширенной матрицы: {rr}')

[[ 2 -4  6]
 [ 1 -2  3]
 [ 3 -6  9]]
[[ 2 -4  6  1]
 [ 1 -2  3 -2]
 [ 3 -6  9  5]]
Ранг матрицы: 1
Ранг расширенной матрицы: 2


б) $rankA<rank \tilde A$ –  система несовместна.

In [21]:
# Задание в) 
import numpy as np
import scipy.linalg
a2 = np.array([[1,2,5],[3,1,-8]])
aa2 = np.array([[1,2,5,4],[3,1,-8,-2]])
r = np.linalg.matrix_rank(a2)
rr = np.linalg.matrix_rank(aa2)
print(a2)
print(aa2)
print(f'Ранг матрицы: {r}')
print(f'Ранг расширенной матрицы: {rr}')

[[ 1  2  5]
 [ 3  1 -8]]
[[ 1  2  5  4]
 [ 3  1 -8 -2]]
Ранг матрицы: 2
Ранг расширенной матрицы: 2


в) $rankA=rank \tilde A<3 $ - число  неизвестных –   система имеет бесконечное количество решений

_3.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}.$$

In [22]:
import numpy as np
import scipy.linalg
a3 = np.array([[1,3,-2, 4],[0,5,0, 1], [0,0,3,0],[0,0,0,2]])
aa3 = np.array([[1,3,-2, 4,3],[0,5,0, 1,2], [0,0,3,0,4],[0,0,0,2,1]])
r = np.linalg.matrix_rank(a3)
rr = np.linalg.matrix_rank(aa3)
print(a3)
print(aa3)
print(f'Ранг матрицы: {r}')
print(f'Ранг расширенной матрицы: {rr}')

[[ 1  3 -2  4]
 [ 0  5  0  1]
 [ 0  0  3  0]
 [ 0  0  0  2]]
[[ 1  3 -2  4  3]
 [ 0  5  0  1  2]
 [ 0  0  3  0  4]
 [ 0  0  0  2  1]]
Ранг матрицы: 4
Ранг расширенной матрицы: 4


 Так как $rankA=rank \tilde A=4$ — число неизвестных, то система определена, т. е. имеет единственное решение;



__4.__ Дана система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}.$$

Найти соотношение между параметрами $a$, $b$ и $c$, при которых система является несовместной.

 Решение: 
$$\begin{pmatrix}
1 & 2 & 3 & a \\ 
0 & 3 & 6& 4a-b \\ 
0 & 0 & 0& a+c-2 
\end{pmatrix}.$$
Нужно, чтобы $a+c-2 \neq 0$ при любых  a  и b. то есть $c \neq  2-a$



__1.__ Решить систему уравнений методом Крамера:

   а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$
Решение: $$x_{1}=\frac{detA_{1}}{detA}= 10/2=5,$$
$$x_{1}=\frac{detA_{1}}{detA}= 4/2=2,$$

   б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$

In [23]:
a = np.array([[2,-1,5], [1,1,-3], [2,4,1]])
print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')

Матрица:
[[ 2 -1  5]
 [ 1  1 -3]
 [ 2  4  1]]
Определитель:
43


In [24]:
a1 = np.array([[10,-1,5], [-2,1,-3], [1,4,1]])
print(f'Матрица:\n{a1}')
print(f'Определитель 1:\n{np.linalg.det(a1):.0f}')
print(f'Х1={np.linalg.det(a1)/np.linalg.det(a):.0f}')

Матрица:
[[10 -1  5]
 [-2  1 -3]
 [ 1  4  1]]
Определитель 1:
86
Х1=2


In [25]:
a2 =  np.array([[2,10,5], [1,-2,-3], [2,1,1]])
print(f'Матрица:\n{a2}')
print(f'Определитель 2:\n{np.linalg.det(a2):.0f}')
print(f'Х2={np.linalg.det(a2)/np.linalg.det(a):.0f}')

Матрица:
[[ 2 10  5]
 [ 1 -2 -3]
 [ 2  1  1]]
Определитель 2:
-43
Х2=-1


In [26]:
a3 =  np.array([[2,-1,10], [1,1,-2], [2,4,1]])
print(f'Матрица:\n{a3}')
print(f'Определитель 3:\n{np.linalg.det(a3):.0f}')
print(f'Х3={np.linalg.det(a3)/np.linalg.det(a):.0f}')

Матрица:
[[ 2 -1 10]
 [ 1  1 -2]
 [ 2  4  1]]
Определитель 3:
43
Х3=1


__2*.__ Найти $L$-матрицу $LU$-разложения для матрицы коэффициентов:

   а)$$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$

In [27]:
U = np.array([[1, 2,4], [0, 5, 4], [0, 0, 2]])
L = np.array([[1, 0,0], [2, 1, 0], [3, 4, 1]])

print(f'Матрица U\n{U}')
print(f'Матрица L\n{L}')
print(f'Матрица LU\n{np.dot(L, U)}')

Матрица U
[[1 2 4]
 [0 5 4]
 [0 0 2]]
Матрица L
[[1 0 0]
 [2 1 0]
 [3 4 1]]
Матрица LU
[[ 1  2  4]
 [ 2  9 12]
 [ 3 26 30]]


б)$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$$

In [28]:
U = np.array([[1, 1,2,4], [0, 3, 4,1], [0, 0, 3,1],[0,0,21,11]])
L = np.array([[1, 0,0,0], [2, 1, 0,0], [3, 5,1,0], [4, 6,0,1]])

print(f'Матрица U\n{U}')
print(f'Матрица L\n{L}')
print(f'Матрица LU\n{np.dot(L, U)}')

Матрица U
[[ 1  1  2  4]
 [ 0  3  4  1]
 [ 0  0  3  1]
 [ 0  0 21 11]]
Матрица L
[[1 0 0 0]
 [2 1 0 0]
 [3 5 1 0]
 [4 6 0 1]]
Матрица LU
[[ 1  1  2  4]
 [ 2  5  8  9]
 [ 3 18 29 18]
 [ 4 22 53 33]]


__3*.__ Решить систему линейных уравнений методом $LU$-разложения

$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$$

Решение:  Матрица коэффициентов имеет вид: $$\begin{pmatrix}
2 & 1 & 3 \\ 
11 & 7 & 5 \\ 
9 & 8 & 4
\end{pmatrix}$$

In [29]:
U = np.array([[2, 1,3], [0, 3/2, -23/2], [0, 0, (-57+23*7)/6]])
L = np.array([[1, 0,0], [11/2, 1, 0], [9/2, 7/3, 1]])

print(f'Матрица U\n{U}')
print(f'Матрица L\n{L}')
print(f'Матрица LU\n{np.dot(L, U)}')

Матрица U
[[  2.           1.           3.        ]
 [  0.           1.5        -11.5       ]
 [  0.           0.          17.33333333]]
Матрица L
[[1.         0.         0.        ]
 [5.5        1.         0.        ]
 [4.5        2.33333333 1.        ]]
Матрица LU
[[ 2.  1.  3.]
 [11.  7.  5.]
 [ 9.  8.  4.]]


$y1=1$

$y2= -11,5$

$y3= -9,5-7/3*23/2$

$x3= (-9.5-7/3*23/2)/  (-57+23*7)/6= -1$

$x2 = -46/3$

$x1 = 29/3$


__4*.__ Решить систему линейных уравнений методом Холецкого

$$\begin{cases}
81x_{1}-45x_{2}+45x_{3}=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}$$

In [30]:
import numpy as np
a = np.array([[81, -45,44], [-45, 50, -15], [45, -15, 38]])
w, v = np.linalg.eig(a)
print(f'Матрица A:\n{a}')
print(f'Матрица A:\n{a.T}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')
print(f'Собственные значения:\n{w}')
L = np.array([[9, 0,0], [-5, 5, 0], [5, 2, 3]])
print(f'Матрица L\n{L}')
print(f'Матрица LLt\n{L@L.T}')
y1=531/9
y2=(-460+5*y1)/5
y3=(193-5*y1-2*y2)/3
print(f'y1={y1}')
print(f'y2={y2}')
print(f'y3={y3}')
print(f'Матрица Lt\n{L.T}')
x3=y3/3
x2=(y2-2*x3)/5
x1=(y1-5*x3+5*x2)/9
print(f'x3={x3}')
print(f'x2={x2}')
print(f'x1={x1}')
print(f'проверка {a@[x1,x2,x3]}')

Матрица A:
[[ 81 -45  44]
 [-45  50 -15]
 [ 45 -15  38]]
Матрица A:
[[ 81 -45  45]
 [-45  50 -15]
 [ 44 -15  38]]
Определитель:
19800
Собственные значения:
[134.39565305   4.97176337  29.63258358]
Матрица L
[[ 9  0  0]
 [-5  5  0]
 [ 5  2  3]]
Матрица LLt
[[ 81 -45  45]
 [-45  50 -15]
 [ 45 -15  38]]
y1=59.0
y2=-33.0
y3=-12.0
Матрица Lt
[[ 9 -5  5]
 [ 0  5  2]
 [ 0  0  3]]
x3=-4.0
x2=-5.0
x1=6.0
проверка [ 535. -460.  193.]
