<a href="https://colab.research.google.com/github/OlegSV117/project/blob/dev-kraken/%D0%9B%D0%B8%D0%BD%D0%90%D0%BB%D0%B33.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

__1.__ Найти собственные векторы и собственные значения для линейного оператора, заданного матрицей

$$A=\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}.$$
Решение: $$(-1-\lambda)\cdot (6-\lambda) + 12 = 0$$
$$ \lambda^2-5\lambda + 6 = 0$$
$$\lambda _{1,2} = (5 \pm \sqrt{25-2*6})/ 2 = 3; 2 $$
$$\lambda _{1} = 3$$
$$\lambda _{2} = 2$$
Собственные вектор  при $\lambda _{1} = 2$:

$$\begin{cases}
-x_{1}-6x_{2}=2 x_{1}, \\
2x_{1}+6x_{2}=2 x_{2}.
\end{cases}$$
$$x_2 =  1; x_1 = -2$$
(-2; 1)

Собственные вектор  при $\lambda _{2} = 3$:
$$\begin{cases}
-x_{1}-6x_{2}=3 x_{1}, \\
2x_{1}+6x_{2}=3 x_{2}.
\end{cases}$$
$$x_2 =  2; x_1 = -3$$

(-3; 2)




In [27]:
import numpy as np
np.set_printoptions(precision=2, suppress=True)
a = np.array([[-1, -6], [2, 6]])
w, v = np.linalg.eig(a)
c1 = np.array([-2, 1])
c2 = np.array([-3, 2])

print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

print(f'v1\n{v.T[0]}')
print(f'v1\n{v.T[1]}')
print(f' проверка найденных вручную собственных векторов')
print(f' для первого собственного значения')
print(f' AC1 = {a@c1}')
print(f'w[0]*c1 = {w[0]*c1}')
print(f' для второго собственного значения')
print(f' AC2 = {a@c2}')
print(f'w[1]*c = {w[1]*c2}')




Матрица A:
[[-1 -6]
 [ 2  6]]
Собственные значения:
[2. 3.]
Собственные векторы:
[[-0.89  0.83]
 [ 0.45 -0.55]]
v1
[-0.89  0.45]
v1
[ 0.83 -0.55]
 проверка найденных вручную собственных векторов
 для первого собственного значения
 AC1 = [-4  2]
w[0]*c1 = [-4.  2.]
 для второго собственного значения
 AC2 = [-9  6]
w[1]*c = [-9.  6.]


__2.__ Дан оператор поворота на 180 градусов, задаваемый матрицей 

$$A=\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}.$$

Показать, что __любой__ вектор является для него собственным.

Доказательство: из характеристического уравнения  $det(A- \lambda I) = (1+\lambda)^2 = 0$
получаем
$\lambda_{1,2} = -1$

Тогда  уравнение на собственные вектора: $$-x_1 = -1\cdot x_1$$
$$-x_2 = -1\cdot x_2$$
Выполнимо для любых $x_1, x_2$

что по определению соответствует матричному тождеству: $(-1)* I*X = (-1) * X$


In [29]:
import numpy as np
np.set_printoptions(precision=2, suppress=True)
a = np.array([[-1, 0], [0, -1]])
w, v = np.linalg.eig(a)
print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[-1  0]
 [ 0 -1]]
Собственные значения:
[-1. -1.]
Собственные векторы:
[[1. 0.]
 [0. 1.]]


__3.__ Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}.$$

Установить, является ли вектор $x=(1,1)$ собственным вектором этого линейного оператора.
Решение: 
из характеристического уравнения  $det(A- \lambda I) = (1+\lambda)(3-\lambda) +1 = \lambda^2 -4\lambda +4 = (\lambda - 2)^2 = 0$
получаем
$\lambda_{1,2} = 2$
То есть хотим показать, что  выполнимо тождество:
$$\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}
\begin{pmatrix}
1\\ 
1
\end{pmatrix}=
2
\begin{pmatrix}
1\\ 
1
\end{pmatrix}.
$$
1+1 = 2
-1+3 = 2
Тождество истино.

In [3]:
import numpy as np
np.set_printoptions(precision=2, suppress=True)
a = np.array([[1, 1], [-1, 3]])
w, v = np.linalg.eig(a)

print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

print(f'v1\n{v.T[0]}')
print(f'v1\n{v.T[1]}')

Матрица A:
[[ 1  1]
 [-1  3]]
Собственные значения:
[2. 2.]
Собственные векторы:
[[ 0.71 -0.71]
 [ 0.71 -0.71]]
v1
[0.71 0.71]
v1
[-0.71 -0.71]


__4.__ Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
0 & 3 & 0\\ 
3 & 0 & 0\\
0 & 0 & 3
\end{pmatrix}.$$

Установить, является ли вектор $x=(3, -3, -4)$ собственным вектором этого линейного оператора.
Решение: вектор $x=(3, -3, -4)$ не является обственным вектором оператора А ни при каких его собственных значениях $\lambda_{1,2,3} = 3; -3; 3$.

In [15]:
import numpy as np
np.set_printoptions(precision=2, suppress=True)
a = np.array([[0, 3, 0], [3, 0, 0], [0, 0, 3]])
c = np.array([3, -3, -4])
w, v = np.linalg.eig(a)

print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')
print(f' AX = {a@c}')
print(f'w[0]*c = {w[0]*c}')
print(f'w[1]*c = {w[1]*c}')
print(f'w[2]*c = {w[2]*c}')


Матрица A:
[[0 3 0]
 [3 0 0]
 [0 0 3]]
Собственные значения:
[ 3. -3.  3.]
 AX = [ -9   9 -12]
w[0]*c = [  9.  -9. -12.]
w[1]*c = [-9.  9. 12.]
w[2]*c = [  9.  -9. -12.]
